dist: trusty
language: c
sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "nlzhYyCXFFisxGhpkVJZCE9N2lL/Vrb6ScmIE1nFdbpp+T8rMbRpwOYiKFgI3RREaY1WCrdR15g827/Mxf8xXhBWeqZ2CmxW7Q3o1zlGXilcmJCATlx9Lok6E/iv6L0Pds3pofP73C5tyfsQAVtLt5rkxmyy5P9ZHugpTYn2eAeEdGk5ikVgJz6Un+yoJfOJ5CS9rM+WTb2NrZ87PTe8nPg3KWOM1kgDE0rFHeTHwxxT7VQIP0MJ4JIWSLSeD+K+9loJLiD6Ow8DrG3kBPEAKRxeDNYF090Dcdut82sg5bSkfv5UXHbe4hef1eq69ptF8OcZNfTXCh8gvpLv5hqCsa/CkUzjaZW1HNrdxO417/MrriV49tl1gmt+wkA8KvHm/HTXnJbqF6GihPlrTgkZZwooi7ABVOGW5Y75jCLx9KYWsBgxt7jjcAKrChAdZXpbmmwrsbU4SiWQAb5uOgKcH1WDoHAPeYQYRrG77wVYBybKLMRwx1qAPwk7RcNmq6/6BUAE5LCiu4nXV7mLyKf7FVk9YFqMQNHRRCXHavcdsw5sgJ8IFSzxRW0e9eYLoAd+hnc86jfD0W5yFNw5LgDAQpiH/hBhE18rHwSgNlyKiLSw7NZS6sXdUzmdKJdnMgNdb8JhM+FeN3m3YwxIBMMkXfU61skU3+t/jHdatMzGUYk="

before_install:
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt-get install libmpfr-dev clang-3.5 llvm-3.5 llvm-3.5-dev dragonegg-4.7 gcc-4.7 g++-4.7 gfortran-4.7 libgfortran-4.7-dev autoconf automake build-essential libedit-dev python3-dev cython3 binutils
  - echo -n | openssl s_client -connect scan.coverity.com:443 -CApath /etc/ssl/certs/  | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

addons:
  coverity_scan:
    project:
      name: verificarlo/verificarlo
      description: A tool for automatic Montecarlo Arithmetic analysis.
    notification_email: yohan.chatelain@gmail.com
    build_command_prepend: cov-configure --template --compiler=gcc-4.7 --comptype=gcc
    build_command: make
    branch_pattern: coverity-travis-CI

install:
  - ./autogen.sh
  - export LIBRARY_PATH=/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7:/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu:/lib/x86_64-linux-gnu:/lib/../lib64:/usr/lib/x86_64-linux-gnu:/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../..:/usr/lib/llvm-3.5/bin/../lib:/lib:/usr/lib:$LIBRARY_PATH
  - ./configure --with-llvm=/usr/lib/llvm-3.5/bin/ --with-dragonegg=/usr/lib/gcc/x86_64-linux-gnu/4.7/plugin/dragonegg.so CC=gcc-4.7 CXX=g++-4.7 || cat config.log
  - make
  - sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - export PYTHONPATH=/usr/local/lib/python3.4/site-packages/:$PYTHONPATH
  - test $TRAVIS_BRANCH == coverity-travis-CI && make clean || exit 0

script:
  - make installcheck
  - for i in $(find tests/ -maxdepth 1 -type d -name 'test_*' | sort ); do echo "************** TEST $i"; cat $i/test.log; done;

