language: c
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clang-3.4 dragonegg gcc-4.6 gfortran-4.6 autoconf automake build-essential
  - git clone https://github.com/mfrechtling/mcalib.git
  - bash -c -l "cd mcalib/ && ./mcasetup.sh"

install:
  - ./autogen.sh
  - ./configure --with-llvm=/usr/bin \
                --with-dragonegg=/usr/lib/gcc/x86_64-linux-gnu/4.6/plugin/dragonegg.so \
                CC=gcc-4.6
  - make

script: make check
