#!/usr/bin/env python3
import xml.etree.ElementTree as etree
import sys
import os

if len(sys.argv) < 2:
	print("./print_range [input file name] functions ...")
	exit(0)

# name of the input file
InputFileName = sys.argv[1]

# list of functions to modify
FunctionsList = sys.argv[2:]

# test if the input file exists
if not os.path.exists(InputFileName):
   	print("Input file not found")
   	exit(0)



tree = etree.parse(InputFileName)

for function in tree.iter("call"):      
    CurrentFunction = function[7].text

    if CurrentFunction in FunctionsList:
        nb_in = int(function[10].text)
        nb_out = int(function[11+nb_in].text)
        
        for i in range(11,11+nb_in):
            arg = function[i]
            print("input:", function[0].text, arg[5].text, arg[6].text)
        
        for i in range(12+nb_in, 12+nb_in+nb_out):
            arg = function[i]
            print("output:", function[0].text, arg[5].text, arg[6].text)            

tree.write(InputFileName)
