#!/usr/bin/env python3
import xml.etree.ElementTree as etree
import sys
import os

if len(sys.argv) < 2:
	print("./print_range [input file name] functions ...")
	exit(0)

# name of the input file
InputFileName = sys.argv[1]

# list of functions to modify
FunctionsList = sys.argv[2:]

# test if the input file exists
if not os.path.exists(InputFileName):
   	print("Input file not found")
   	exit(0)



tree = etree.parse(InputFileName)

for function in tree.iter("function"):
    
    CurrentFunction = function[0].text.split(sep="/")[1] + "/" + function[0].text.split(sep="/")[2]

    if CurrentFunction in FunctionsList:

        for arg in function.iter("input"):
            print("input:", function[0].text, arg[4].text, arg[5].text)
    
        for arg in function.iter("output"):
            print("output:", function[0].text, arg[4].text, arg[5].text)

tree.write(InputFileName)