name: clang-format-lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.6
      with:
        exclude: './tests'
        style: 'LLVM'
